version: '3'
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Manasoko@1
      MYSQL_DATABASE: student_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: manajay/student-api:1.0.0
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    command: npm start
    environment:
      NODE_ENV: development
      PORT: 8080
      DATABASE_NAME: student_db
      DATABASE_USER: root
      DATABASE_PASSWORD: Manasoko@1
    depends_on:
      mysql:
        condition: service_healthy


volumes:
  db_data: