name: Student API CI/CD Pipeline

on:
  push:
    branches:
     - main
    paths:
     - 'src/**/*.ts'
     - 'tests/**/*.ts'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22.x'

      - name: Install Dependencies
        run: make install

      - name: Build Node Project
        run: make build

  docker:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          make docker-build

      - name: Push Docker Image
        run: |
          make docker-push

  